-- Table
DROP TABLE users CASCADE;
DROP TABLE wiki CASCADE;
DROP TABLE chats CASCADE;
DROP TABLE chat_messages CASCADE;
DROP TABLE activity CASCADE;
DROP TABLE lessons CASCADE;
DROP TABLE lesson_items CASCADE;
